doctors = [
    {
        "id": 1,
        "name": "دکتر سارا جانسون",
        "profession": "متخصص قلب و عروق",
        "title": "متخصص ارشد قلب و عروق",
        "description": "متخصص در قلب‌شناسی مداخله‌ای و مدیریت نارسایی قلبی با بیش از ۱۵ سال تجربه در درمان بیماری‌های پیچیده قلبی.",
        "specialties": ["قلب‌شناسی مداخله‌ای", "نارسایی قلبی", "اکوکاردیوگرافی"],
        "experience_years": 15,
        "education": "دکترای تخصصی قلب - دانشگاه هاروارد",
        "hospital": "بیمارستان قلب و عروق مهر",
        "location": "تهران، خیابان ولیعصر",
        "rating": 409,
        "reviews_count": 342,
        "availability": ["شنبه", "دوشنبه", "چهارشنبه"],
        "consultation_fee": 250,
        "phone": "۰۲۱-۵۵۵۵-۰۱۲۳",
        "email": "dr.sarah.johnson@memorialheart.com",
        "is_accepting_patients": True,
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "sarah_johnson.jpg"
    },
    {
        "id": 2,
        "name": "دکتر مایکل چن",
        "profession": "متخصص مغز و اعصاب",
        "title": "رئیس بخش مغز و اعصاب",
        "description": "متخصص در اختلالات نورودژنراتیو و توانبخشی سکته مغزی. تحقیقات پیشگام در زمینه بیماری آلزایمر و درمان پارکینسون.",
        "specialties": ["اختلالات نورودژنراتیو", "توانبخشی سکته مغزی", "اختلالات حرکتی"],
        "experience_years": 20,
        "education": "دکترای تخصصی و فوق دکترای علوم اعصاب - دانشگاه جانز هاپکینز",
        "hospital": "مرکز علوم اعصاب پاسیفیک",
        "location": "مشهد، بلوار وکیل‌آباد",
        "rating": 408,
        "reviews_count": 287,
        "availability": ["یکشنبه", "سه‌شنبه", "پنجشنبه"],
        "consultation_fee": 300,
        "phone": "۰۵۱-۵۵۵۵-۰۴۵۶",
        "email": "dr.michael.chen@pacificneuro.com",
        "is_accepting_patients": True,
        "languages": ["فارسی", "انگلیسی", "ماندارین"],
        "profile_image": "michael_chen.jpg"
    },
    {
        "id": 3,
        "name": "دکتر امیلی رودریگز",
        "profession": "متخصص کودکان",
        "title": "متخصص اطفال دارای بورد تخصصی",
        "description": "ارائه‌دهنده مراقبت‌های دلسوزانه کودکان با تمرکز بر رشد و تکامل کودک، پزشکی پیشگیرانه و سلامت نوجوانان. متعهد به ارائه مراقبت‌های خانواده‌محور.",
        "specialties": ["رشد و تکامل کودک", "پزشکی نوجوانان", "ایمونولوژی کودکان"],
        "experience_years": 12,
        "education": "دکترای تخصصی کودکان و بهداشت عمومی - دانشگاه استنفورد",
        "hospital": "مرکز سلامت کودکان",
        "location": "شیراز، خیابان زند",
        "rating": 409,
        "reviews_count": 415,
        "availability": ["شنبه", "یکشنبه", "سه‌شنبه", "چهارشنبه"],
        "consultation_fee": 180,
        "phone": "۰۷۱-۵۵۵۵-۰۷۸۹",
        "email": "dr.emily.rodriguez@childrenswellness.com",
        "is_accepting_patients": False,
        "languages": ["فارسی", "انگلیسی", "اسپانیایی"],
        "profile_image": "emily_rodriguez.jpg"
    },
   
    {
        "id": 4,
        "name": "دکتر جیمز ویلسون",
        "profession": "جراح ارتوپد",
        "title": "مدیر بخش جراحی ارتوپدی",
        "description": "جراح ارتوپد برجسته متخصص در پزشکی ورزشی، تعویض مفصل و تکنیک‌های جراحی کم‌تهاجمی. همکاری با ورزشکاران حرفه‌ای و افراد فعال.",
        "specialties": ["پزشکی ورزشی", "تعویض مفصل", "آرتروسکوپی", "جراحی ستون فقرات"],
        "experience_years": 18,
        "education": "دکترای تخصصی ارتوپدی - کلینیک مایو",
        "hospital": "مرکز تخصصی ارتوپدی",
        "location": "اصفهان، چهارباغ بالا",
        "rating": 407,
        "reviews_count": 198,
        "availability": ["شنبه", "دوشنبه", "چهارشنبه"],
        "consultation_fee": 350,
        "phone": "۰۳۱-۵۵۵۵-۰۴۵۶",
        "email": "dr.james.wilson@premierortho.com",
        "is_accepting_patients": True,
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "james_wilson.jpg"
    },
    {
        "id": 47,
        "name": "دکتر سارا رحیمی",
        "profession": "متخصص دندانپزشکی ترمیمی و زیبایی",
        "title": "رییس بخش دندانپزشکی ترمیمی",
        "description": "متخصص برجسته دندانپزشکی ترمیمی و زیبایی با تمرکز بر درمان‌های بدون درد، لمینت سرامیکی، ایمپلنت‌های دیجیتال و ارتودنسی نامرئی. همکار رسمی کلینیک‌های بین‌المللی و عضو انجمن دندانپزشکی زیبایی اروپا.",
        "specialties": ["ایمپلنت دیجیتال", "لمینت سرامیکی", "ارتودنسی نامرئی (اینویزیلاین)", "درمان ریشه (اندو)", "جراحی لثه", "بلیچینگ پیشرفته"],
        "experience_years": 14,
        "education": "فلوشیپ ایمپلنتولوژی - دانشگاه برن سوئیس",
        "hospital": "کلینیک تخصصی دندانپزشکی مدرن",
        "location": "تهران، خیابان ولیعصر، بالاتر از میدان ونک، پلاک ۱۲۳",
        "rating": 489,
        "reviews_count": 234,
        "availability": ["شنبه", "یکشنبه", "سه‌شنبه", "پنجشنبه"],
        "consultation_fee": 280,
        "phone": "۰۲۱-۸۸۷۷-۱۲۳۴",
        "email": "dr.sara.rahimi@moderndental.com",
        "is_accepting_patients": True,
        "languages": ["فارسی", "انگلیسی", "آلمانی (مقدماتی)"],
        "profile_image": "sara_rahimi.jpg"
    },
    {
        "id": 5,
        "name": "دکتر پریا شارما",
        "profession": "متخصص پوست",
        "title": "متخصص بالینی پوست",
        "description": "متخصص در پوست‌شناسی پزشکی، جراحی و زیبایی. تخصص در تشخیص سرطان پوست، درمان اگزما و درمان‌های پیشرفته لیزر برای بیماری‌های مختلف پوستی.",
        "specialties": ["تشخیص سرطان پوست", "درمان اگزما", "درمان با لیزر", "پوست‌شناسی زیبایی"],
        "experience_years": 10,
        "education": "دکترای تخصصی پوست - دانشگاه پنسیلوانیا",
        "hospital": "مرکز پوست و مراقبت‌های زیبایی",
        "location": "تبریز، خیابان امام خمینی",
        "rating": 408,
        "reviews_count": 256,
        "availability": ["یکشنبه", "سه‌شنبه", "پنجشنبه"],
        "consultation_fee": 220,
        "phone": "۰۴۱-۵۵۵۵-۰۸۹۹",
        "email": "dr.priya.sharma@dermskincare.com",
        "is_accepting_patients": True,
        "languages": ["فارسی", "انگلیسی", "هندی"],
        "profile_image": "priya_sharma.jpg"
    }
]

doctors_plus_10 = [
    {
        "id": 2,
        "name": "دکتر امیر حسینی",
        "profession": "متخصص مغز و اعصاب",
        "title": "فلوشیپ صرع و اختلالات خواب",
        "description": "متخصص تشخیص و درمان بیماری‌های عصبی با تمرکز بر صرع مقاوم به درمان و اختلالات حرکتی، با سابقه پژوهش در دانشگاه جانز هاپکینز.",
        "specialties": ["صرع", "اختلالات خواب", "بیماری‌های حرکتی", "EMG/NCV"],
        "experience_years": 12,
        "education": "فلوشیپ صرع - جانز هاپکینز، دکترای تخصصی اعصاب - دانشگاه تهران",
        "hospital": "بیمارستان فوق تخصصی نور",
        "location": "تهران، خیابان آزادی، نبش کشاورز",
        "rating": 4.8,
        "reviews_count": 287,
        "availability": ["یکشنبه", "سه‌شنبه", "پنجشنبه"],
        "schedule": {
            "یکشنبه": {"start": "08:00", "end": "16:00", "slots": 32},
            "سه‌شنبه": {"start": "10:00", "end": "18:00", "slots": 28},
            "پنجشنبه": {"start": "08:00", "end": "14:00", "slots": 24}
        },
        "consultation_fee": 320,
        "phone": "۰۲۱-۵۵۴۳-۲۱۰۹",
        "email": "dr.amer.hosseini@nurhospital.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی", "آلمانی"],
        "profile_image": "amir_hosseini.jpg"
    },
    
    {
        "id": 3,
        "name": "دکتر لیلا کریمی",
        "profession": "متخصص زنان و زایمان",
        "title": "جراح لاپاراسکوپی و فلوشیپ ناباروری",
        "description": "ارائه‌دهنده خدمات کامل سلامت زنان از دوران بلوغ تا یائسگی، با تخصص در جراحی‌های پیشرفته لاپاراسکوپی و درمان ناباروری.",
        "specialties": ["ناباروری", "جراحی لاپاراسکوپی", "زایمان طبیعی و سزارین", "اندومتریوز"],
        "experience_years": 18,
        "education": "فلوشیپ ناباروری - دانشگاه شهید بهشتی، جراحی لاپاراسکوپی - فرانسه",
        "hospital": "بیمارستان تخصصی مادر و کودک",
        "location": "شیراز، خیابان ملاصدرا، مجتمع پزشکی پارس",
        "rating": 4.9,
        "reviews_count": 415,
        "availability": ["شنبه", "دوشنبه", "چهارشنبه", "پنجشنبه"],
        "schedule": {
            "شنبه": {"start": "09:00", "end": "15:00", "slots": 24},
            "دوشنبه": {"start": "09:00", "end": "19:00", "slots": 40},
            "چهارشنبه": {"start": "09:00", "end": "17:00", "slots": 30},
            "پنجشنبه": {"start": "08:00", "end": "13:00", "slots": 20}
        },
        "consultation_fee": 280,
        "phone": "۰۷۱-۳۲۲۴-۵۵۶۶",
        "email": "dr.leila.karimi@motherchild.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "leila_karimi.jpg"
    },
    {
        "id": 4,
        "name": "دکتر محمدرضا بهرامی",
        "profession": "متخصص ارتوپدی",
        "title": "جراح تعویض مفصل و آرتروسکوپی",
        "description": "بیش از ۲۰ سال تجربه در جراحی‌های تعویض مفصل زانو و لگن و آرتروسکوپی شانه و زانو، با استفاده از جدیدترین متدهای کم‌تهاجمی.",
        "specialties": ["تعویض مفصل زانو", "تعویض مفصل لگن", "آرتروسکوپی شانه", "ترمیم رباط"],
        "experience_years": 20,
        "education": "دکترای تخصصی ارتوپدی - دانشگاه علوم پزشکی ایران، فلوشیپ تعویض مفصل - آلمان",
        "hospital": "بیمارستان تخصصی ارتوپدی حضرت رسول",
        "location": "مشهد، بلوار وکیل‌آباد، بیمارستان رسول",
        "rating": 4.7,
        "reviews_count": 198,
        "availability": ["یکشنبه", "سه‌شنبه", "چهارشنبه"],
        "schedule": {
            "یکشنبه": {"start": "08:00", "end": "16:00", "slots": 35},
            "سه‌شنبه": {"start": "08:00", "end": "18:00", "slots": 40},
            "چهارشنبه": {"start": "08:00", "end": "14:00", "slots": 25}
        },
        "consultation_fee": 350,
        "phone": "۰۵۱-۳۲۲۱-۷۸۹۰",
        "email": "dr.mr.bahrami@rasoulortho.com",
        "is_accepting_patients": "false",
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "mr_bahrami.jpg"
    },
    {
        "id": 5,
        "name": "دکتر الناز شریفی",
        "profession": "متخصص پوست و مو",
        "title": "فلوشیپ زیبایی و لیزر درمانی",
        "description": "پزشک پوست با تمرکز بر درمان ضایعات پوستی، بیماری‌های خودایمنی پوست، و روش‌های پیشرفته جوانسازی و لیزر درمانی.",
        "specialties": ["درماتولوژی بالینی", "لیزر درمانی", "پوست و مو", "زیبایی پزشکی"],
        "experience_years": 10,
        "education": "فلوشیپ لیزر درمانی - دانشگاه علوم پزشکی تهران، دکترای تخصصی پوست - شهید بهشتی",
        "hospital": "کلینیک تخصصی پوست و موی سپید",
        "location": "اصفهان، خیابان چهارباغ بالا، کوچه ۲۴",
        "rating": 4.9,
        "reviews_count": 521,
        "availability": ["شنبه", "دوشنبه", "پنجشنبه"],
        "schedule": {
            "شنبه": {"start": "10:00", "end": "18:00", "slots": 30},
            "دوشنبه": {"start": "10:00", "end": "20:00", "slots": 42},
            "پنجشنبه": {"start": "09:00", "end": "14:00", "slots": 20}
        },
        "consultation_fee": 220,
        "phone": "۰۳۱-۳۳۵۵-۴۴۸۸",
        "email": "dr.elnaz.sharifi@sepidehclinic.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی", "فرانسوی"],
        "profile_image": "elnaz_sharifi.jpg"
    },
    {
        "id": 6,
        "name": "دکتر کیوان نوروزی",
        "profession": "متخصص گوارش و کبد",
        "title": "فلوشیپ آندوسکوپی پیشرفته و بیماری‌های کبدی",
        "description": "متخصص تشخیص و درمان بیماری‌های گوارشی، کبدی و کیسه صفرا با استفاده از آندوسکوپی تشخیصی و درمانی پیشرفته (ERCP، EUS).",
        "specialties": ["بیماری‌های کبد", "آندوسکوپی پیشرفته", "بیماری التهابی روده", "سنگ کیسه صفرا"],
        "experience_years": 14,
        "education": "فلوشیپ آندوسکوپی پیشرفته - دانشگاه علوم پزشکی شیراز، دکترای گوارش - تهران",
        "hospital": "بیمارستان فوق تخصصی کبد و گوارش",
        "location": "تهران، خیابان انقلاب، پلاک ۴۵۶",
        "rating": 4.6,
        "reviews_count": 210,
        "availability": ["یکشنبه", "دوشنبه", "چهارشنبه"],
        "schedule": {
            "یکشنبه": {"start": "08:30", "end": "15:30", "slots": 28},
            "دوشنبه": {"start": "09:00", "end": "19:00", "slots": 40},
            "چهارشنبه": {"start": "08:30", "end": "14:30", "slots": 24}
        },
        "consultation_fee": 300,
        "phone": "۰۲۱-۶۶۴۴-۱۲۳۴",
        "email": "dr.keyvan.norouzi@gihepat.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "keyvan_norouzi.jpg"
    },
    {
        "id": 7,
        "name": "دکتر سیمین سعیدی",
        "profession": "متخصص کودکان",
        "title": "فوق تخصص بیماری‌های غدد و متابولیک کودکان",
        "description": "پزشک اطفال با تمرکز بر اختلالات رشد، دیابت کودکان، بیماری‌های تیروئید و اختلالات متابولیک مادرزادی با رویکردی خانواده‌محور.",
        "specialties": ["دیابت کودکان", "اختلالات رشد", "بیماری‌های تیروئید", "متابولیک مادرزادی"],
        "experience_years": 16,
        "education": "فوق تخصص غدد کودکان - دانشگاه علوم پزشکی اصفهان، دکترای کودکان - شیراز",
        "hospital": "بیمارستان تخصصی کودکان امیرکبیر",
        "location": "تبریز، بلوار استاد شهریار، بیمارستان امیرکبیر",
        "rating": 4.8,
        "reviews_count": 375,
        "availability": ["شنبه", "سه‌شنبه", "پنجشنبه"],
        "schedule": {
            "شنبه": {"start": "08:00", "end": "14:00", "slots": 22},
            "سه‌شنبه": {"start": "09:00", "end": "17:00", "slots": 32},
            "پنجشنبه": {"start": "08:00", "end": "12:00", "slots": 16}
        },
        "consultation_fee": 200,
        "phone": "۰۴۱-۳۲۲۴-۵۸۷۶",
        "email": "dr.simin.saeedi@amirkabirkids.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی", "ترکی"],
        "profile_image": "simin_saeedi.jpg"
    },
    {
        "id": 8,
        "name": "دکتر فرهاد جمشیدی",
        "profession": "متخصص چشم‌پزشکی",
        "title": "جراح قرنیه و اصلاح عیوب انکساری",
        "description": "جراح مجرب در پیوند قرنیه، رفرکتیو سرفری (LASIK، PRK) و درمان بیماری‌های سطح قدامی چشم با بهره‌گیری از تکنولوژی‌های روز.",
        "specialties": ["جراحی قرنیه", "LASIK و PRK", "بیماری‌های سطح قدامی", "پیوند قرنیه"],
        "experience_years": 22,
        "education": "فلوشیپ جراحی قرنیه - دانشگاه علوم پزشکی تهران، دکترای تخصصی چشم - شهید بهشتی",
        "hospital": "بیمارستان چشم‌پزشکی نور",
        "location": "تهران، خیابان پاسداران، خیابان گلستان، پلاک ۱۲",
        "rating": 4.9,
        "reviews_count": 623,
        "availability": ["یکشنبه", "دوشنبه", "چهارشنبه", "پنجشنبه"],
        "schedule": {
            "یکشنبه": {"start": "08:00", "end": "16:00", "slots": 35},
            "دوشنبه": {"start": "08:00", "end": "18:00", "slots": 38},
            "چهارشنبه": {"start": "08:00", "end": "16:00", "slots": 35},
            "پنجشنبه": {"start": "07:30", "end": "12:00", "slots": 18}
        },
        "consultation_fee": 400,
        "phone": "۰۲۱-۲۲۸۸-۱۱۱۱",
        "email": "dr.farhad.jamshidi@noreye.com",
        "is_accepting_patients": "false",
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "farhad_jamshidi.jpg"
    },
    {
        "id": 9,
        "name": "دکتر ندا مرادی",
        "profession": "متخصص روانپزشکی",
        "title": "فلوشیپ روانپزشکی کودک و نوجوان",
        "description": "ارائه خدمات تشخیصی و درمانی در حوزه افسردگی، اختلالات اضطرابی، اختلال نقص توجه/بیش‌فعالی (ADHD) و اختلالات طیف اوتیسم در کودکان و بزرگسالان.",
        "specialties": ["روانپزشکی کودک", "اختلالات اضطرابی", "افسردگی", "ADHD و اوتیسم"],
        "experience_years": 13,
        "education": "فلوشیپ روانپزشکی کودک - دانشگاه علوم پزشکی تهران، روانپزشکی عمومی - ایران",
        "hospital": "مرکز تخصصی سلامت روان مهر",
        "location": "کرج، بلوار مطهری، خیابان هفتم",
        "rating": 4.7,
        "reviews_count": 189,
        "availability": ["شنبه", "دوشنبه", "چهارشنبه"],
        "schedule": {
            "شنبه": {"start": "10:00", "end": "18:00", "slots": 20},
            "دوشنبه": {"start": "10:00", "end": "20:00", "slots": 25},
            "چهارشنبه": {"start": "09:00", "end": "17:00", "slots": 22}
        },
        "consultation_fee": 270,
        "phone": "۰۲۶-۳۲۲۵-۶۶۷۷",
        "email": "dr.neda.moradi@mehrmind.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی"],
        "profile_image": "neda_moradi.jpg"
    },
    {
        "id": 10,
        "name": "دکتر بهروز کاظمی",
        "profession": "متخصص کلیه و مجاری ادراری (اورولوژی)",
        "title": "جراح لاپاراسکوپی و فلوشیپ سرطان‌های دستگاه ادراری",
        "description": "تشخیص و درمان سنگ‌های کلیوی، نارسایی کلیه، سرطان پروستات و مثانه با استفاده از جراحی‌های کم‌تهاجمی و رباتیک.",
        "specialties": ["جراحی کلیه", "سرطان پروستات", "سنگ کلیه", "پیوند کلیه"],
        "experience_years": 17,
        "education": "فلوشیپ سرطان اورولوژی - دانشگاه علوم پزشکی مشهد، جراحی لاپاراسکوپی - کره جنوبی",
        "hospital": "بیمارستان تخصصی کلیه و مجاری ادراری",
        "location": "رشت، خیابان گلسار، بیمارستان شهید انصاری",
        "rating": 4.8,
        "reviews_count": 256,
        "availability": ["یکشنبه", "سه‌شنبه", "چهارشنبه"],
        "schedule": {
            "یکشنبه": {"start": "08:00", "end": "15:00", "slots": 28},
            "سه‌شنبه": {"start": "08:00", "end": "18:00", "slots": 35},
            "چهارشنبه": {"start": "08:00", "end": "14:00", "slots": 25}
        },
        "consultation_fee": 330,
        "phone": "۰۱۳-۳۲۲۴-۱۱۲۲",
        "email": "dr.behrouz.kazemi@urologyansari.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی", "گیلکی"],
        "profile_image": "behrouz_kazemi.jpg"
    },
    {
        "id": 11,
        "name": "دکتر مریم السادات حسینی",
        "profession": "متخصص گوش، حلق و بینی (ENT)",
        "title": "فلوشیپ جراحی پایه جمجمه و کاشت حلزون",
        "description": "ارائه خدمات تشخیصی و جراحی در زمینه اختلالات شنوایی، تعادل، سینوزیت‌های مزمن و جراحی‌های پیشرفته گوش و پایه جمجمه.",
        "specialties": ["کاشت حلزون", "جراحی سینوس", "اختلالات تعادل", "جراحی پایه جمجمه"],
        "experience_years": 19,
        "education": "فلوشیپ جراحی پایه جمجمه - دانشگاه علوم پزشکی تهران، ENT عمومی - شهید بهشتی",
        "hospital": "بیمارستان فوق تخصصی گوش و حلق و بینی",
        "location": "قم، بلوار شهید صدوقی، نبش کوچه ۹",
        "rating": 4.9,
        "reviews_count": 402,
        "availability": ["شنبه", "دوشنبه", "پنجشنبه"],
        "schedule": {
            "شنبه": {"start": "09:00", "end": "17:00", "slots": 30},
            "دوشنبه": {"start": "09:00", "end": "19:00", "slots": 40},
            "پنجشنبه": {"start": "08:00", "end": "13:00", "slots": 20}
        },
        "consultation_fee": 310,
        "phone": "۰۲۵-۳۶۶۶-۷۷۸۸",
        "email": "dr.maryam.hosseini@entqom.com",
        "is_accepting_patients": "true",
        "languages": ["فارسی", "انگلیسی", "عربی"],
        "profile_image": "maryam_hosseini.jpg"
    }
]

# # Example usage - displaying doctor information in Persian
# for doctor in doctors:
#     print(f"دکتر {doctor['name']} - {doctor['profession']}")
#     print(f"  عنوان: {doctor['title']}")
#     print(f"  توضیحات: {doctor['description'][:50]}...")
#     print(f"  آدرس: {doctor['location']}")
#     print(f"  امتیاز: {doctor['rating']} ⭐ ({doctor['reviews_count']} نظر)")
#     print(f"  هزینه ویزیت: {doctor['consultation_fee']} تومان")
#     print(f"  تخصص‌ها: {', '.join(doctor['specialties'])}")
#     print(f"  روزهای ویزیت: {', '.join(doctor['availability'])}")
#     print(f"  زبان‌ها: {', '.join(doctor['languages'])}")
#     print("-" * 60)